# Generated by Django 2.2.5 on 2020-05-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='PortalWebScrappingEmpleo',
        ),
    ]
